// UnitTests/Helpers/CollectiveArtifactFixtures.swift
import Foundation
import XCTest
@testable import Pilgrim

/// The two artifacts every collective-route test runs against, and the one
/// decode both go through.
///
/// They are kept together because the whole risk in this feature is that they
/// stop agreeing. `collectiveParityFixtureJSON` is a transcription; the bundled
/// file is regenerated on demand by `scripts/regen-route-bootstrap.sh`. Nothing
/// forces them to match, and every pinned selection vector in this target is a
/// property of the transcription — so drift silently turns 60-odd passing
/// assertions into a description of a pool the app no longer uses.
/// `CollectiveRouteBundledArtifactTests` is the guard that makes that loud.

/// Decoded exactly as `CollectiveRouteCatalogService` decodes it: a stock
/// `JSONDecoder` with no configuration, which is what the service holds.
func decodeCatalog(_ data: Data) throws -> CollectiveRouteCatalog {
    try JSONDecoder().decode(CollectiveRouteCatalog.self, from: data)
}

/// The artifact that actually ships in the app bundle.
enum BundledCollectiveArtifact {

    static let resourceName = "collective-routes-bootstrap"

    /// Resolved through `Bundle.main`, not `Bundle(for:)`. UnitTests runs hosted
    /// by Pilgrim.app, so the main bundle of the running process is the app
    /// bundle — which is the only one carrying this file. The test target's own
    /// copy-resources phase is empty, so `Bundle(for:)` finds nothing here.
    static func url() throws -> URL {
        try XCTUnwrap(
            Bundle.main.url(forResource: resourceName, withExtension: "json"),
            "\(resourceName).json is missing from the app bundle — run scripts/regen-route-bootstrap.sh and check the Pilgrim target's Copy Bundle Resources phase"
        )
    }

    static func data() throws -> Data {
        try Data(contentsOf: url())
    }

    static func decoded() throws -> CollectiveRouteCatalog {
        try decodeCatalog(try data())
    }
}

/// The shipped artifact at `../pilgrim-landing/assets/collective-routes.json`
/// with `reflections` and `annual` stripped — iOS decodes neither of them.
///
/// Every `webPicks` and `webLines` vector was generated by running
/// `../pilgrim-landing/js/collective-routes.js` over *this* entry set. Changing
/// it without regenerating them, or regenerating the bundled artifact without
/// changing it, breaks the parity suite's meaning rather than its result.
let collectiveParityFixtureJSON = Data("""
{
  "version": "0faeb638520c",
  "pilgrimages": [
    { "id": "camino-frances", "kind": "route", "nameEn": "Camino de Santiago", "companyLine": "242,179 pilgrims completed it in 2025.", "km": 764, "bestMonths": [5,6,9], "peakMonths": [7,8] },
    { "id": "camino-ingles", "kind": "route", "nameEn": "Camino Inglés", "companyLine": "30,204 pilgrims completed it in 2025.", "km": 112, "bestMonths": [4,5,6,9,10], "peakMonths": [7,8] },
    { "id": "camino-norte", "kind": "route", "nameEn": "Camino del Norte", "companyLine": "21,521 pilgrims completed it in 2025.", "km": 784, "bestMonths": [5,6,9], "peakMonths": [7,8] },
    { "id": "camino-portugues", "kind": "route", "nameEn": "Camino Portugués", "companyLine": "100,839 pilgrims completed it in 2025.", "km": 243, "bestMonths": [4,5,6,9,10], "peakMonths": [7,8] },
    { "id": "camino-primitivo", "kind": "route", "nameEn": "Camino Primitivo", "companyLine": "27,871 pilgrims completed it in 2025.", "km": 263, "bestMonths": [5,6,9], "peakMonths": [7,8] },
    { "id": "kumano-kodo", "kind": "route", "nameEn": "Kumano Kodo", "companyLine": "44,540 foreign visitors stayed overnight near Hongu in 2024.", "km": 39, "bestMonths": [3,4,5,10,11], "peakMonths": [4,5,10,11] },
    { "id": "shikoku-88", "kind": "route", "nameEn": "Shikoku 88 Temple Pilgrimage", "companyLine": "About 150,000 made the circuit in 2025; 1,622 on foot.", "km": 1200, "bestMonths": [3,4,5,10,11], "peakMonths": [4,10] }
  ],
  "horizons": [
    { "id": "around-earth", "kind": "cosmic", "preposition": "around", "body": "the Earth", "companyLine": "A handful have ever walked it; the first finished in 1974.", "km": 40075 },
    { "id": "to-the-moon", "kind": "cosmic", "preposition": "to", "body": "the Moon", "companyLine": "No one has ever walked it.", "km": 384400 },
    { "id": "to-the-sun", "kind": "cosmic", "preposition": "to", "body": "the Sun", "companyLine": "No one ever will.", "km": 149600000 }
  ]
}
""".utf8)
