-- Migration number: 0001 generated by teenybase on 2026-03-22T13:28:06.738Z. Do not modify this file.

CREATE TABLE notes (
	id TEXT PRIMARY KEY NOT NULL, 
	created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, 
	updated TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, 
	owner_id TEXT NOT NULL REFERENCES users(id), 
	title TEXT NOT NULL, 
	content TEXT NOT NULL, 
	is_public BOOLEAN NOT NULL DEFAULT 0, 
	slug TEXT UNIQUE NOT NULL, 
	tags TEXT, 
	meta JSON, 
	cover TEXT, 
	views INTEGER DEFAULT 0, 
	archived BOOLEAN DEFAULT 0, 
	deleted_at TIMESTAMP DEFAULT NULL
);
CREATE INDEX idx_notes_owner_id ON notes (owner_id);
CREATE INDEX idx_notes_tags ON notes (tags COLLATE NOCASE);
CREATE INDEX idx_notes_is_public ON notes (is_public);
CREATE INDEX idx_notes_archived ON notes (archived);
CREATE INDEX idx_notes_deleted_at ON notes (deleted_at);
CREATE TRIGGER tgr_notes_raise_on_created_update BEFORE UPDATE OF created ON notes BEGIN SELECT RAISE(FAIL, 'Cannot update created column') WHERE OLD.created != NEW.created; END;CREATE VIRTUAL TABLE fts5_notes_idx USING fts5(title, content, tags, tokenize=trigram, content="notes");
INSERT INTO fts5_notes_idx(rowid, title, content, tags) SELECT rowid, title, content, tags FROM notes;
CREATE TRIGGER fts5_notes_idx_ai AFTER INSERT ON notes BEGIN
    INSERT INTO fts5_notes_idx(rowid, title, content, tags) VALUES (new.rowid, new.title, new.content, new.tags);
END;
CREATE TRIGGER fts5_notes_idx_ad AFTER DELETE ON notes BEGIN
    INSERT INTO fts5_notes_idx(fts5_notes_idx, rowid, title, content, tags) VALUES ('delete', old.rowid, old.title, old.content, old.tags);
END;
CREATE TRIGGER fts5_notes_idx_au AFTER UPDATE ON notes BEGIN
    INSERT INTO fts5_notes_idx(fts5_notes_idx, rowid, title, content, tags) VALUES ('delete', old.rowid, old.title, old.content, old.tags);
    INSERT INTO fts5_notes_idx(rowid, title, content, tags) VALUES (new.rowid, new.title, new.content, new.tags);
END;