-- Migration number: 0002 generated by teenybase on 2026-03-22T13:28:06.739Z. Do not modify this file.

CREATE TABLE kv_store (
	key TEXT PRIMARY KEY NOT NULL, 
	value JSON NOT NULL, 
	expire TIMESTAMP
);