import XCTest
@testable import Pilgrim

final class EtegamiTextGeneratorTests: XCTestCase {

    func testUserIntention_takesPriority() {
        let text = EtegamiTextGenerator.generate(
            intention: "finding peace in motion",
            reflection: nil,
            season: "Spring", timeOfDay: "Morning",
            durationMinutes: 45, moonPhaseName: nil,
            weatherCondition: nil, primaryActivity: .walking
        )
        XCTAssertEqual(text, "finding peace in motion")
    }

    func testUserReflection_takesPriority() {
        let text = EtegamiTextGenerator.generate(
            intention: nil,
            reflection: "The trail was quiet today",
            season: "Autumn", timeOfDay: "Evening",
            durationMinutes: 30, moonPhaseName: nil,
            weatherCondition: nil, primaryActivity: .walking
        )
        XCTAssertEqual(text, "The trail was quiet today")
    }

    func testAutoGenerated_containsThreeLines() {
        let text = EtegamiTextGenerator.generate(
            intention: nil, reflection: nil,
            season: "Winter", timeOfDay: "Morning",
            durationMinutes: 45, moonPhaseName: "Waning Crescent",
            weatherCondition: "rain", primaryActivity: .meditation
        )
        let lines = text.components(separatedBy: "\n")
        XCTAssertEqual(lines.count, 3)
    }

    func testAutoGenerated_includesSeason() {
        let text = EtegamiTextGenerator.generate(
            intention: nil, reflection: nil,
            season: "Spring", timeOfDay: "Morning",
            durationMinutes: 30, moonPhaseName: nil,
            weatherCondition: nil, primaryActivity: .walking
        )
        XCTAssertTrue(text.lowercased().contains("spring"))
    }

    func testAutoGenerated_moonTakesPriorityOverWeather() {
        let text = EtegamiTextGenerator.generate(
            intention: nil, reflection: nil,
            season: "Summer", timeOfDay: "Night",
            durationMinutes: 60, moonPhaseName: "Full Moon",
            weatherCondition: "rain", primaryActivity: .walking
        )
        XCTAssertTrue(text.contains("full moon"))
    }

    func testAutoGenerated_weatherUsedWhenNoMoon() {
        let text = EtegamiTextGenerator.generate(
            intention: nil, reflection: nil,
            season: "Autumn", timeOfDay: "Afternoon",
            durationMinutes: 20, moonPhaseName: nil,
            weatherCondition: "rain", primaryActivity: .voice
        )
        XCTAssertTrue(text.contains("rain"))
    }

    func testAutoGenerated_meditationActivity() {
        let text = EtegamiTextGenerator.generate(
            intention: nil, reflection: nil,
            season: "Spring", timeOfDay: "Morning",
            durationMinutes: 30, moonPhaseName: nil,
            weatherCondition: nil, primaryActivity: .meditation
        )
        XCTAssertTrue(text.contains("stillness"))
    }

    func testIntention_priorityOverReflection() {
        let text = EtegamiTextGenerator.generate(
            intention: "my intention",
            reflection: "my reflection",
            season: "Spring", timeOfDay: "Morning",
            durationMinutes: 30, moonPhaseName: nil,
            weatherCondition: nil, primaryActivity: .walking
        )
        XCTAssertEqual(text, "my intention")
    }
}
